### ISSUE TITLE
[Feature request]: Add 'initial' processingState. Update processingState when adding to queue

### ISSUE THREAD

**Issue by leflings** [Setono/SyliusImagePlugin#27]
### Describe the proposed solution

- [ ] Add a new processingState `initial` which will be the default value.
- [ ] When images are added to queue it must transition into `pending` state (this indicates that it has been added to the queue)
- [ ] It should be possible to move into the `pending` state from the following states `initial`, `processed`, `failed`
- [ ] Add a lock to the `ProcessCommand`
- [ ] `ProcessCommand` should look for images in one of the following states: `initial`, `processed`, `failed`
- [ ] `TimeoutCommand` should look for images in one of the following states: `pending`, `processing`

**Comment by loevgaard** [comment]
Could this be divided into multiple PRs? :)
